package com.techfox.ui.theme

import androidx.compose.ui.graphics.Color

// Light Amber Scheme
val AmberPrimaryLight = Color(0xFF8B5000)
val AmberOnPrimaryLight = Color(0xFFFFFFFF)
val AmberPrimaryContainerLight = Color(0xFFFFDCC2)
val AmberOnPrimaryContainerLight = Color(0xFF2C1600)
val AmberSecondaryContainerLight = Color(0xFFF6DFC8)
val AmberOnSecondaryContainerLight = Color(0xFF271905)
val AmberTertiaryContainerLight = Color(0xFFD5EDC0)
val AmberOnTertiaryContainerLight = Color(0xFF0E2004)
val AmberSurfaceLight = Color(0xFFFFF8F5)
val AmberSurfaceContainerLowLight = Color(0xFFFCF1EA)
val AmberSurfaceContainerLight = Color(0xFFF7ECE4)
val AmberSurfaceContainerHighLight = Color(0xFFF3E6DE)
val AmberSurfaceContainerHighestLight = Color(0xFFEDE0D8)
val AmberOnSurfaceLight = Color(0xFF211A14)
val AmberOnSurfaceVariantLight = Color(0xFF51443B)
val AmberOutlineLight = Color(0xFF83746A)
val AmberOutlineVariantLight = Color(0xFFD6C3B6)
val AmberInverseSurfaceLight = Color(0xFF362F28)
val AmberInverseOnSurfaceLight = Color(0xFFFBEEE5)
val AmberInversePrimaryLight = Color(0xFFFFB77C)
val AmberErrorLight = Color(0xFFB3261E)
val AmberOnErrorLight = Color(0xFFFFFFFF)
val AmberErrorContainerLight = Color(0xFFF9DEDC)
val AmberOnErrorContainerLight = Color(0xFF410E0B)

// Dark Amber Scheme
val AmberPrimaryDark = Color(0xFFFDB976)
val AmberOnPrimaryDark = Color(0xFF472A07)
val AmberPrimaryContainerDark = Color(0xFF683C05)
val AmberOnPrimaryContainerDark = Color(0xFFFDDDC1)
val AmberSecondaryContainerDark = Color(0xFF59422E)
val AmberOnSecondaryContainerDark = Color(0xFFFBDDC4)
val AmberTertiaryContainerDark = Color(0xFF384D25)
val AmberOnTertiaryContainerDark = Color(0xFFD2EABA)
val AmberSurfaceDark = Color(0xFF17130F)
val AmberSurfaceContainerLowDark = Color(0xFF1F1B18)
val AmberSurfaceContainerDark = Color(0xFF231F1C)
val AmberSurfaceContainerHighDark = Color(0xFF2D2926)
val AmberSurfaceContainerHighestDark = Color(0xFF383431)
val AmberOnSurfaceDark = Color(0xFFE7E1DD)
val AmberOnSurfaceVariantDark = Color(0xFFD1C4BA)
val AmberOutlineDark = Color(0xFF9A8F85)
val AmberOutlineVariantDark = Color(0xFF4F453D)
val AmberInverseSurfaceDark = Color(0xFFE7E1DD)
val AmberInverseOnSurfaceDark = Color(0xFF34302C)
val AmberInversePrimaryDark = Color(0xFF8B5000)
val AmberErrorDark = Color(0xFFF2B8B5)
val AmberOnErrorDark = Color(0xFF601410)
val AmberErrorContainerDark = Color(0xFF8C1D18)
val AmberOnErrorContainerDark = Color(0xFFF9DEDC)

